#!/bin/bash

# Cập nhật hệ thống
sudo apt update && sudo apt upgrade -y

# Cài đặt các tiện ích cần thiết
sudo apt install -y curl

# Cài đặt NodeJS phiên bản mới nhất
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs

# Cài đặt Docker
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update
sudo apt install -y docker-ce

# Thêm người dùng hiện tại vào nhóm Docker để chạy Docker mà không cần sudo
sudo usermod -aG docker $USER

# Cài đặt Git
sudo apt install -y git

# Hiển thị phiên bản của các phần mềm đã cài đặt
echo "NodeJS version:"
node -v
echo "NPM version:"
npm -v
echo "Docker version:"
docker --version
echo "Git version:"
git --version
